In [ ]:
import numpy as np

In [ ]:
# Create rating table
R = np.array([
    [5, 3, 0, 1, 4],
    [4, 0, 0, 2, 2],
    [4, 5, 4, 3, 0],
    [0, 3, 1, 0, 5]
])

R

array([[5, 3, 0, 1, 4],
       [4, 0, 0, 2, 2],
       [4, 5, 4, 3, 0],
       [0, 3, 1, 0, 5]])

In [ ]:
#latent features
k = 2

# Number of users & movies
num_users, num_movies = R.shape
num_users, num_movies

(4, 5)

In [ ]:
# Randomly initialize Users and Movie Matrix
U = np.random.rand(num_users, k)
M = np.random.rand(num_movies, k)
U, M

(array([[0.24202341, 0.2762628 ],
        [0.10622544, 0.19228434],
        [0.53912364, 0.1468079 ],
        [0.69386656, 0.19807458]]),
 array([[0.77288779, 0.25721997],
        [0.94302926, 0.05532219],
        [0.31898713, 0.34981769],
        [0.4788649 , 0.72218816],
        [0.17924279, 0.3532978 ]]))

In [ ]:
V = M.transpose()
V

array([[0.77288779, 0.94302926, 0.31898713, 0.4788649 , 0.17924279],
       [0.25721997, 0.05532219, 0.34981769, 0.72218816, 0.3532978 ]])

In [ ]:
np.dot(U, V)

array([[0.25811724, 0.24351862, 0.17384397, 0.31541024, 0.14098399],
       [0.13155972, 0.11081129, 0.10114901, 0.18973311, 0.08697378],
       [0.454444  , 0.5165311 , 0.2233295 , 0.36419031, 0.14850093],
       [0.58722973, 0.66529439, 0.2906245 , 0.47531546, 0.19434989]])

In [ ]:
# Hyperparameters
num_iterations = 10000
learning_rate = 0.01

In [ ]:
# Perform matrix factorization with SGD
for i in range(num_iterations):
  for u in range(num_users):
    for m in range(num_movies):
      if R[u, m] > 0:
        error = R[u, m] - np.dot(U[u, :], V[:, m])
        U[u, :] += learning_rate * (2 * error * V[:, m])
        V[:, m] += learning_rate * (2 * error * U[u, :])

U, V

(array([[ 0.69279738,  1.11914133],
        [ 0.3780887 ,  1.05708368],
        [ 5.81123721, -0.953835  ],
        [ 0.84528017,  1.04396103]]),
 array([[ 1.26634906,  1.17616299,  0.74629551,  0.68254205,  6.39954907],
        [ 3.518733  ,  1.922101  ,  0.35249006,  1.02160513, -0.39215444]]))

In [ ]:
# Reconstruct Matrix R from new U & V
R_hat = np.dot(U, V)
R_hat

array([[ 4.81528285,  2.96594532,  0.91151777,  1.61618387,  3.99471456],
       [ 4.19838751,  2.47651555,  0.65477739,  1.33798355,  2.00505711],
       [ 4.00276408,  5.00159494,  4.0006829 ,  2.99197103, 37.56334829],
       [ 4.74383987,  3.0007858 ,  0.99881468,  1.64345521,  5.000018  ]])

In [ ]:
# Display the results
print("Original Rating Table:")
print(R)
print("\nReconstructed Rating Table:")
R_hat_rounded = np.clip(np.round(R_hat), 1, 5).astype(int)
print(R_hat_rounded)

Original Rating Table:
[[5 3 0 1 4]
 [4 0 0 2 2]
 [4 5 4 3 0]
 [0 3 1 0 5]]

Reconstructed Rating Table:
[[5 3 1 2 4]
 [4 2 1 1 2]
 [4 5 4 3 5]
 [5 3 1 2 5]]


In [ ]:

# Print original matrix with highlighted 0 values
print("Original Matrix: ")
for row_idx, row in enumerate(R):
    for col_idx, val in enumerate(row):
        if val == 0:
            print('\033[91m' + str(val) + '\033[0m', end=' ')  # Print in red color
        else:
            print(val, end=' ')
    print()  # Newline for next row

# Print predicted matrix with highlighted predicted values
print("Predicted Matrix: ")
for row_idx, row in enumerate(R_hat_rounded):
    for col_idx, val in enumerate(row):
        if R[row_idx, col_idx] == 0:  # If original value is 0
            print('\033[92m' + str(val) + '\033[0m', end=' ')  # Print predicted value in green color
        else:
            print(val, end=' ')  # Print predicted value
    print()  # Newline for next row


Original Matrix: 
5 3 0 1 4 
4 0 0 2 2 
4 5 4 3 0 
0 3 1 0 5 
Predicted Matrix: 
5 3 1 2 4 
4 2 1 1 2 
4 5 4 3 5 
5 3 1 2 5 
